version: '2'
services:
  web:
    # build: .
    image: petclinic/petclinic:${BUILD_NUMBER}
    ports:
      - '9090:8080'
    environment:
      - DB_HOST=mysql:3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - INIT_DB=true
    restart: on-failure
