version: '2'
services:
  mysql:
    image: 'mysql:5.7'
    restart: always
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=petclinic
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  web:
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql:3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - INIT_DB=true
    restart: on-failure

volumes:
  mysql:
