version: '2'
services:
  mysql:
    ports:
      - '3306:3306'

  web:
    image: java:8
    entrypoint: ["./mvnw"]
    command: ["spring-boot:run"]
    ports:
      - '9966:9966'
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mysql:
