---
- name: Configure CI server
  hosts: ci-server
  sudo: True
  roles:
    - role: openmicroscopy.docker
    - role: emmetog.jenkins
      jenkins_install_via: "yum"
      jenkins_home: /var/lib/jenkins
      jenkins_include_secrets: true
      jenkins_config_owner: "jenkins"
      jenkins_config_group: "jenkins"
      jenkins_plugins:
        - ace-editor
        - ant
        - antisamy-markup-formatter
        - apache-httpcomponents-client-4-api
        - authentication-tokens
        - bouncycastle-api
        - branch-api
        - build-pipeline-plugin
        - build-timeout
        - cloudbees-folder
        - command-launcher
        - conditional-buildstep
        - credentials
        - credentials-binding
        - display-url-api
        - docker-build-step
        - docker-commons
        - docker-workflow
        - durable-task
        - email-ext
        - external-monitor-job
        - git
        - git-client
        - github
        - github-api
        - github-branch-source
        - git-server
        - handlebars
        - jackson2-api
        - javadoc
        - jquery
        - jquery-detached
        - jsch
        - junit
        - ldap
        - mailer
        - matrix-auth
        - matrix-project
        - maven-plugin
        - momentjs
        - pam-auth
        - parameterized-trigger
        - pipeline-build-step
        - pipeline-github-lib
        - pipeline-graph-analysis
        - pipeline-input-step
        - pipeline-milestone-step
        - pipeline-model-api
        - pipeline-model-declarative-agent
        - pipeline-model-definition
        - pipeline-model-extensions
        - pipeline-rest-api
        - pipeline-stage-step
        - pipeline-stage-tags-metadata
        - pipeline-stage-view
        - plain-credentials
        - resource-disposer
        - run-condition
        - scm-api
        - script-security
        - ssh-credentials
        - structs
        - timestamper
        - token-macro
        - windows-slaves
        - workflow-aggregator
        - workflow-api
        - workflow-basic-steps
        - workflow-cps
        - workflow-cps-global-lib
        - workflow-durable-task-step
        - workflow-job
        - workflow-multibranch
        - workflow-scm-step
        - workflow-step-api
        - workflow-support
        - ws-cleanup
